### PR TITLE
YAG-35-add-search-button-to-controls-panel

### PR DESCRIPTION
**Pull request by S4kRiPp4**
@chillyssa helped with guiding me with my struggles

Basically, added a search text field, search button with a icon next to it. I also reorganized the code and left comments so that its easier to scroll through and read. 

I also added in a working logout and a back button that takes you to the previous page. I commented them out because I could not get them to align where I wanted them. If anyone wants to mess with alignment just remove the // before the tabelPanel.add(logoutButton) and tabelPanel.add(backButton) on lines 169, and 176. Then they will display when you run our project.

search textfield/button's goal hopefully tomorrow is to function with SQL db and perform readOne.

### CODE REVIEW

**Comment by S4kRiPp4** [comment]
line 105 and line 112 are the lines your would remove the comment, not 169 & 176. Sorry I'm tired.

**Review by chillyssa — APPROVED** [review]
Nice job with this. I also like the addition of the placeholder text in the search text field. When we integrate the navigation buttons, the focus of the component will be fixed as well so the placeholder text shows when the page first loads. 

To properly display those buttons we will need to probably alter how we are currently implementing the layout manager for header Panel. I added a navigation menu as an employee user story with subtasks into the Jira board to tackle this - https://yagni-inc.atlassian.net/browse/YAG-39

**Comment by S4kRiPp4** [comment]
> Nice job with this. I also like the addition of the placeholder text in the search text field. When we integrate the navigation buttons, the focus of the component will be fixed as well so the placeholder text shows when the page first loads.
> 
> To properly display those buttons we will need to probably alter how we are currently implementing the layout manager for header Panel. I added a navigation menu as an employee user story with subtasks into the Jira board to tackle this - https://yagni-inc.atlassian.net/browse/YAG-39

yup the focus works correctly when ran with the logout/back button.

**Review by KyleZim97 — APPROVED** [review]
You walked me through the changes you had and it looks great. I like where you put the search field and how it is styled. You also organized the code better and that looks good too.

**Pull request merged**
