### PR TITLE
updated the old deleteRecord() method to work with the SQL database

### PR DESCRIPTION
**Pull request by sethharling**
hi there :)

### CODE REVIEW

**Review by KyleZim97 — APPROVED** [review]
Yeah, looks good! We should probably just remove that commented code out but we can do that when go through an overall formatting of the app.

**Comment by snowjtSD** [comment]
looks good to merge to me!

**Review by snowjtSD — COMMENTED** [review]
All good for me!

**Review by KyleZim97 — APPROVED** [review]
already reviewed all good.

**Review by chillyssa — APPROVED** [review]
Looks good to me. I agree with @KyleZim97 about removing commented code in a refactoring effort! 
Nice work @sethharling

**Pull request merged**
