### PR TITLE
Added ordersGUI class and added a new GUI

### PR DESCRIPTION
**Pull request by Jesusxx-240**
I made another class called OrdersGUI and added another window displaying text that will show up after hitting the "ordersButton", and I also added code in the override method to get it to work.

### CODE REVIEW

**Review by S4kRiPp4 — CHANGES_REQUESTED** [review]
looks good, I would just change all the label/frame names in the ManageInventoryGUI from 

userFrame / userLabel  to --> inventoryFrame/inventoryLabel , to avoid confusion when we work on the class later

**Review by chillyssa — DISMISSED** [review]
Nice work! I do agree with @S4kRiPp4's comment about updating the label variables to closer match the class for uniformity.

**Review by S4kRiPp4 — APPROVED** [review]
👍

**Review by chillyssa — APPROVED** [review]
Thanks for updating those labels @Jesusxx-240! Looking good!

**Pull request merged**
