### PR TITLE
Updated the readAll and readOne methods to work with the DB

### PR DESCRIPTION
**Pull request by KyleZim97**
Co-authored-by: Jordan Snow [jsnow7@msudenver.edu](mailto:jsnow7@msudenver.edu)

Jordan and I updated the readOne and readAll methods to work with the database
Did some formatting for the user instructions
Removed unused imports
Updated the password input so that it is not visible when typing it in

### CODE REVIEW

**Review by chillyssa — APPROVED** [review]
This looks good to me. Nice job @KyleZim97  and @snowjtSD!

**Review by chillyssa — APPROVED** [review]
There were merge conflicts with main.  I reviewed and resolved duplicate import statements and variable declarations. Resubmitting my PR approval!

**Comment by snowjtSD** [comment]
viewed the changes made and everything seems to look functional to me, still not sure what was occurring with my old laptop that caused formatting issues but since I'm migrating to a new device shouldn't be a problem anymore.

**Review by snowjtSD — APPROVED** [review]
Looks good next sprint I will go through the code and clean some things we don't need going forward as we focus on using databases but let's talk about this Tuesday after demo's

**Pull request merged**
