### PR TITLE
Added a help menu in the menu bar

### PR DESCRIPTION
**Pull request by Jesusxx-240**
Also added a Help section in our MenuBar just to give it a little more professional look. The assistance button just shows a message for now. This is open to add more functionality or other stuff in the future too. 
Screen Shot 2022-04-17 at 12 48 01 PM

### CODE REVIEW

**Review by snowjtSD — APPROVED** [review]
Good stuff time to blow Jesse up with help requests

**Comment by S4kRiPp4** [comment]
> Good stuff time to blow Jesse up with help requests

I'll make sure to forward all calls to our Senior Help Specialist aka Jordan lol

**Review by S4kRiPp4 — APPROVED** [review]
Looks good great addition, 3 hour holds until a customer gives up seems very likely. 

Only thing I would suggest is waiting for your other PR to merge(#72 I think), before merging this. Since both PR's are open and have changes inside OrdersGUI.java there might be a merge conflict. 

If you want to be safe you could use this as a draft and then fetch upstream and re-push this w/ all the changes from your other PR. I don't feel like going line by line to see if it will have conflicts but just so that your aware.

Also, adding another "File" menu item that we talked about would be a neat addition too.

I won't merge yet but I'll leave open for more reviewers/insights.

**Review by S4kRiPp4 — CHANGES_REQUESTED** [review]
This branch has conflicts that must be resolved.

I just noticed that error, so just move this to a draft or close it and push again after your other PR is merged. I'm guessing it's cause both PR's have changes in OrdersGUI.java

**Review by S4kRiPp4 — APPROVED** [review]

**Pull request merged**
