### PR TITLE
Formatted the print statements for organized console UI 

### PR DESCRIPTION
**Pull request by chillyssa**
Added formatting to the UI of the console application

### CODE REVIEW

**Comment by chillyssa** [comment]
[Test Application and Format Console UI](https://trello.com/c/uHPA2IZI/6-test-application-and-format-console-ui)

**Review by S4kRiPp4 — APPROVED** [review]
looks good, I plan on cleaning up a little more later today after MTH Hw w/ a .trim method

**Review by S4kRiPp4 — CHANGES_REQUESTED** [review]
add System.out.println("-------------------------------------"); above line 56
I will add in .trim methods after sprint 1 to clean up user input(if they accidently have extra spaces etc.) il switch of a few of the println() methods to print() so that it looks cleaner when user is interacting with our program.

**Comment by chillyssa** [comment]
@S4kRiPp4 I added the requested change, should be good to go!

**Review by S4kRiPp4 — APPROVED** [review]
Sweet!

**Review by KyleZim97 — APPROVED** [review]
Yep, looks good. The instruction to the users looks more clear and concise.

**Comment by KyleZim97** [comment]
Just merged the pull request.

**Pull request merged**
