### PR TITLE
applied file structure changes

### PR DESCRIPTION
**Pull request by sethharling**
used git in command line to move/rename files

last commit/merge did not fully apply changed of files. This commit should actually apply the changes, as I used the git mv command via the command line to move/rename the files. For future reference, if you want to rename or move a file within the file structure, use the git mv command.

### CODE REVIEW

**Review by snowjtSD — APPROVED** [review]
thanks for refactoring that.

**Comment by sethharling** [comment]
solved conflicts from previous commit by merging main into this branch.

**Review by S4kRiPp4 — APPROVED** [review]
I approve but not going to merge, someone else can If they want but we shouldn't be merging something like this the day before presentation. I noticed the file changes are just switching things to lowercase so risk vs. reward isn't worth it for me.

Also, was wondering if you could rename the file under model from Main.java to something else? I noticed you renamed it last time you refactored but wasn't sure why. Myself and Kyle ran the wrong Main.java while programming a few times. There is a Main.java under model which is our original app through keyboard commands and then Main.java under view is the GUI/webpage app. 2 totally different files but have the same name.

Renaming the Main.java under model will also need further changes for everything that referenced that file. We were going to change it to something else but it caused a bunch of errors since other files were dependent on it. Wasn't really in our scope so we just left it alone.

**Review by chillyssa — CHANGES_REQUESTED** [review]
I agree with @S4kRiPp4 about having two files named Main.java. Although they are in separate folders we may run into issues with compiling/running in the future. Is it possible to make this change before we merge this? 

Since we don't use the Main.java that housed our old App.java in our first application iteration I suggest we name that file to TestMain or CommandMain to denote that it is an instance of our older command line application. Since we use the GUI Main as our main entry point of our application I think that keeping that one as Main.java is appropriate.

**Comment by sethharling** [comment]
Did not see @chillyssa 's comment at first so I had to make two commits, but I changed the Main file in the model folder (the terminal interface program) into TestMain.java, and left the GUI interface file inside of the view folder as Main.java.

**Review by chillyssa — APPROVED** [review]
Thanks for making this change @sethharling! looks good to merge.

**Pull request merged**
