### PR TITLE
Logout/back-buttons

### PR DESCRIPTION
**Pull request by S4kRiPp4**
Added logout/back buttons to most pages that are fully functional

Changed code in login class so the Login successful or Invalid credentials will remove it self once navigating to a different page

### CODE REVIEW

**Comment by S4kRiPp4** [comment]
the second commit was because I realized I need to add/delete comments and remove blank spaces. And to do one last read through/test to make sure everything was working as intended.

**Review by KyleZim97 — APPROVED** [review]
Looks good to me. Its my opinion that we close the connection to the database when we click the logout button. I just remembered we have not closed it anywhere yet so we will need to do that and I think the logout button is a great place to do that. I can do that after we get this code merged or you could re-push with the change.

**Comment by S4kRiPp4** [comment]
> Looks good to me. Its my opinion that we close the connection to the database when we click the logout button. I just remembered we have not closed it anywhere yet so we will need to do that and I think the logout button is a great place to do that. I can do that after we get this code merged or you could re-push with the change.

yeah I'll probably need your help with that, I already tried and it's not pretty.

**Review by chillyssa — CHANGES_REQUESTED** [review]
I checked this out locally to be able to see the physical changes. Thanks for powering through the difficulties with the layouts and having to make each page different to work for what we need!!

For better UI/UX I would suggest making the buttons slightly taller so the text size looks more proportionate to the button, like 40px and then moving the buttons slightly on the x,y scale to add some margin to the frame- so for back do like (15,15,100,40) and logout (780, 15, 100, 40). What do you think about these changes?

**Comment by S4kRiPp4** [comment]
> I checked this out locally to be able to see the physical changes. Thanks for powering through the difficulties with the layouts and having to make each page different to work for what we need!!
> 
> For better UI/UX I would suggest making the buttons slightly taller so the text size looks more proportionate to the button, like 40px and then moving the buttons slightly on the x,y scale to add some margin to the frame- so for back do like (15,15,100,40) and logout (780, 15, 100, 40). What do you think about these changes?

yeah I already messed around with the X coordinate a lot. if you look at the padding I gave the Backbutton it's only 5, and the logoutButton padding is 20 after all the math. You would think it would end up being equal but its not. I can try messing with the height and see but i tried to match the height of the other buttons inside each .java class. But I'll add the Y padding now.

The text size seemed to be inherited from which ever Frame/panel it belonged too so changing that changes everything inside. Hard to explain but if you have a solution I will try it.

**Comment by chillyssa** [comment]
> > I checked this out locally to be able to see the physical changes. Thanks for powering through the difficulties with the layouts and having to make each page different to work for what we need!!
> > For better UI/UX I would suggest making the buttons slightly taller so the text size looks more proportionate to the button, like 40px and then moving the buttons slightly on the x,y scale to add some margin to the frame- so for back do like (15,15,100,40) and logout (780, 15, 100, 40). What do you think about these changes?
> 
> yeah I already messed around with the X coordinate a lot. if you look at the padding I gave the Backbutton it's only 5, and the logoutButton padding is 20 after all the math. You would think it would end up being equal but its not. I can try messing with the height and see but i tried to match the height of the other buttons inside each .java class. But I'll add the Y padding now.
> 
> The text size seemed to be inherited from which ever Frame/panel it belonged too so changing that changes everything inside. Hard to explain but if you have a solution I will try it.

I did see the back button has an x bounds of 5. Upping the x bounds for the back button to 20(originally I said 15) would make the space on the left hand side of the button the same spacing as the right hand side of the logout button on the opposite side. I know it's a small change but having aligned margins on both sides adds to the overall UX of the app. 

As for the font, my solution would be to change the height of the button to 40px so that the text fits more proportionately inside the button. Another solution would be to alter the text size in the font definition area using the .deriveFont() method, however I think the default size is actually an appropriate readable size and don't know if making it smaller would be the best route for UI/UX overall.

**Comment by S4kRiPp4** [comment]
let me know what you think @chillyssa . I padded the Y axis, added text alignments. I didn't move the X axis because I aligned Logout off of the button below it on ManageInventoryGUI.java file. I figured it would be better to keep everything uniform to that same padding for all the windows so it doesn't look bizarre when navigating between things. I increased the heights too let me know if you see anything else.

**Comment by S4kRiPp4** [comment]
> > > I checked this out locally to be able to see the physical changes. Thanks for powering through the difficulties with the layouts and having to make each page different to work for what we need!!
> > > For better UI/UX I would suggest making the buttons slightly taller so the text size looks more proportionate to the button, like 40px and then moving the buttons slightly on the x,y scale to add some margin to the frame- so for back do like (15,15,100,40) and logout (780, 15, 100, 40). What do you think about these changes?
> > 
> > 
> > yeah I already messed around with the X coordinate a lot. if you look at the padding I gave the Backbutton it's only 5, and the logoutButton padding is 20 after all the math. You would think it would end up being equal but its not. I can try messing with the height and see but i tried to match the height of the other buttons inside each .java class. But I'll add the Y padding now.
> > The text size seemed to be inherited from which ever Frame/panel it belonged too so changing that changes everything inside. Hard to explain but if you have a solution I will try it.
> 
> I did see the back button has an x bounds of 5. Upping the x bounds for the back button to 20(originally I said 15) would make the space on the left hand side of the button the same spacing as the right hand side of the logout button on the opposite side. I know it's a small change but having aligned margins on both sides adds to the overall UX of the app.
> 
> As for the font, my solution would be to change the height of the button to 40px so that the text fits more proportionately inside the button. Another solution would be to alter the text size in the font definition area using the .deriveFont() method, however I think the default size is actually an appropriate readable size and don't know if making it smaller would be the best route for UI/UX overall.

so the padding for the X axis on my end is the same for both buttons, idk i could screenshot and share but changing it to that 20 makes them off for me

**Comment by S4kRiPp4** [comment]
UX

**Comment by chillyssa** [comment]
> UX

Ok we definitely have a mac/windows OS display difference here! Here is what mine looks like: 
macOS UX

Let's leave the x-axis on the back button alone but changing the button heights to be uniform across all the pages is ideal.

**Comment by S4kRiPp4** [comment]
> > UX
> 
> Ok we definitely have a mac/windows OS display difference here! Here is what mine looks like: macOS UX
> 
> Let's leave the x-axis on the back button alone but changing the button heights to be uniform across all the pages is ideal.

yeah I see how we both have different alignments now I thought you were messing with me haha

**Comment by chillyssa** [comment]
> > > UX
> > 
> > 
> > Ok we definitely have a mac/windows OS display difference here! Here is what mine looks like: macOS UX
> > Let's leave the x-axis on the back button alone but changing the button heights to be uniform across all the pages is ideal.
> 
> yeah I see how we both have different alignments now I thought you were messing with me haha

Haha, I am definitely glad we did the screen share because I was questioning my own sanity

**Review by chillyssa — APPROVED** [review]
Awesome. Thanks for making these changes. looks great and now we have an awareness of spacing differences between Mac/Windows for future design concerns.

**Pull request merged**
