### PR TITLE
YAG-41-integrate-create-functionality-with-manage-inventory-gui

### PR DESCRIPTION
**Pull request by KyleZim97**
Co-Authored Alyssa Williams @chillyssa 

Added the Create class that adds a record to the products table.

### CODE REVIEW

**Review by S4kRiPp4 — COMMENTED** [review]
I'll finish tomorrow, just wanted to know exactly what's going on since were integrating the GUI w/ SQL. So I can give a review with substance rather just hitting, Approve.

**Review by snowjtSD — COMMENTED** [review]
after code review looks good and thanks for the breakdown of what was done and how it is working.

**Review by sethharling — APPROVED** [review]
looks good, also i changed the file name from dbConnection.java to DbConnection.java.

**Review by S4kRiPp4 — CHANGES_REQUESTED** [review]
I would change that "connection" variable name to avoid confusion. possible something like linkSQL or connectSQL. kinda hard to tell if its the variable being used or a inbuilt method. Other than that looks great.

**Review by S4kRiPp4 — COMMENTED** [review]
idk if we should use the dbconnection as the new name since Dbconnection is the class name. like line 20 in Create.java says (Dbconnection dbConnection)

**Comment by chillyssa** [comment]
> idk if we should use the dbconnection as the new name since Dbconnection is the class name. like line 20 in Create.java says (Dbconnection dbConnection)

Apologies I didn't see your suggestion in the earlier comment. I will make that change now and re-push!

**Comment by S4kRiPp4** [comment]
> > idk if we should use the dbconnection as the new name since Dbconnection is the class name. like line 20 in Create.java says (Dbconnection dbConnection)
> 
> Apologies I didn't see your suggestion in the earlier comment. I will make that change now and re-push!

no worries, sorry for the repetitive changes lol

**Review by S4kRiPp4 — APPROVED** [review]
sweet thanks Allyssa, the new variable name clears my brain fog.  We will need to stay consistent with using linkDB w/ all our new class files coming this week.

**Comment by S4kRiPp4** [comment]
great work Kyle and Alyssa.

**Pull request merged**
