### PR TITLE
YAG-42-connect-login-gui-with-database-connection

### PR DESCRIPTION
**Pull request by chillyssa**
Co-authored-by: Kyle Zimmerman @KyleZim97 

This pull request introduces the integration of the SQL connect method into the LoginGUI page. The user can now establish a connection to the sql server with typing in their root/password combination. The hard coded username and password are no longer needed!

We copied the logic into the LoginGUI.java but did NOT remove it from App.java in the event we need to rework the code further.

### CODE REVIEW

**Review by KyleZim97 — APPROVED** [review]
Yes, I worked on this code and it works. Not sure if that's how we are meant to do it. But it works!

**Comment by chillyssa** [comment]
Altering this pull request in favor of incoming changes from @KyleZim97 with alternative implementation using Connection Class to maintain one database connection throughout the application.

**Review by KyleZim97 — APPROVED** [review]
Alyssa and I wrote this code and reviewed it together.

**Review by snowjtSD — COMMENTED** [review]
Just reviewing the code not for approval or anything just checking the changes here. Way to clean up and refactor the fields and variables here step in the direction we want when it comes to cleaning up our code and compartmentalizing things.

**Pull request merged**
