### PR TITLE
Added addRecord method to main.

### PR DESCRIPTION
**Pull request by KyleZim97**
I also changed variable names and data types in case 1 of the switch case and added a call method for the addRecord.

### CODE REVIEW

**Review by Jesusxx-240 — APPROVED** [review]
It looks good, I saw you run the code so I know it will work well. Later on we can talk about a way to possibly merge both the delete and add method together to reduce code.

**Comment by KyleZim97** [comment]
[Refactor Add Class to addRecord method](https://trello.com/c/dgGIhIwZ/12-refactor-add-class-to-addrecord-method)

**Review by snowjtSD — APPROVED** [review]
looks good on the changes, good idea to compartmentalize the scanner for the sake of not having to account and close multiple instances of a scanner!

**Review by snowjtSD — APPROVED** [review]
same comments regarding last review, just had to redo an approval to merge changes.

**Review by chillyssa — APPROVED** [review]
Looking great, our application is coming together nicely! Excited for Tuesday's demo!

**Pull request merged**
